#!/usr/bin/env python3
"""Generates docs/generated/RECORDS.md from the record! and coded_enum! macros.

The wire formats are declared once, in Rust. This script reads those
declarations and writes the reference tables, so the documentation cannot
drift from the code.

usage: tools/gen_records.py [--check]
  --check   exit 1 if the generated file is out of date (used in CI)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "generated" / "RECORDS.md"

MACRO_RE = re.compile(r"\b(record|coded_enum)!\s*\{")


def macro_bodies(text: str):
    """Yields (macro name, body) for each invocation, matching braces by hand."""
    for m in MACRO_RE.finditer(text):
        # Skip invocations inside doc comments and the macro definitions themselves.
        line_start = text.rfind("\n", 0, m.start()) + 1
        prefix = text[line_start:m.start()]
        if prefix.lstrip().startswith("//") or "macro_rules" in text[max(0, m.start() - 40):m.start()]:
            continue
        depth, i = 1, m.end()
        while i < len(text) and depth:
            depth += (text[i] == "{") - (text[i] == "}")
            i += 1
        yield m.group(1), text[m.end():i - 1]
STRUCT_RE = re.compile(r"((?:\s*///[^\n]*\n)*)\s*(?:#\[[^\]]*\]\s*)*pub struct (\w+)\s*\{(.*)\}", re.S)
FIELD_RE = re.compile(r"((?:\s*///[^\n]*\n)*)\s*(\d+)\s*=>\s*(\w+)\s*:\s*([^,\n]+(?:<[^\n]*>)?[^,\n]*),", re.S)
ENUM_HEAD_RE = re.compile(r"((?:\s*///[^\n]*\n)*)\s*(?:#\[[^\]]*\]\s*)*pub enum (\w+)\s*:\s*(\w+)\s*\{(.*)\}", re.S)
VARIANT_RE = re.compile(r"((?:\s*///[^\n]*\n)*)\s*(\w+)\s*=\s*(\d+)\s*=>\s*\"([^\"]*)\"", re.S)


def doc(text: str) -> str:
    lines = [l.strip()[3:].strip() for l in text.strip().splitlines() if l.strip().startswith("///")]
    return " ".join(lines)


def scan():
    records, enums = [], []
    for path in sorted((ROOT / "crates").rglob("*.rs")):
        if "/tests" in str(path) or path.name == "tests.rs" or "/bin/" in str(path):
            continue
        text = path.read_text()
        rel = path.relative_to(ROOT)
        for kind, body in macro_bodies(text):
            if kind == "record":
                s = STRUCT_RE.search(body)
                if not s:
                    continue
                fields = [(int(k), n, " ".join(t.split()), doc(d)) for d, k, n, t in FIELD_RE.findall(s.group(3) + ",")]
                records.append((s.group(2), doc(s.group(1)), fields, str(rel)))
            else:
                e = ENUM_HEAD_RE.search(body)
                if not e:
                    continue
                variants = [(int(c), t, doc(d)) for d, _n, c, t in VARIANT_RE.findall(e.group(4))]
                enums.append((e.group(2), doc(e.group(1)), variants, str(rel)))
    return records, enums


def render() -> str:
    records, enums = scan()
    out = [
        "# Generated record and enumeration reference",
        "",
        "<!-- GENERATED by tools/gen_records.py from the Rust sources. Do not edit by hand. -->",
        "",
        "Every JLR record is a CBOR map with **integer keys**, encoded as JLR-DCBOR/1 (see",
        "[INTEGRITY_PROTOCOL.md](../INTEGRITY_PROTOCOL.md)). An `Option<T>` field is **omitted** when absent and never",
        "written as `null`; an unknown key, a missing required key, a wrong type, or an encoding that is not the",
        "canonical one is an error. Enumerations are unsigned integers on the wire; their names are for humans.",
        "",
        "## Records",
        "",
    ]
    for name, d, fields, src in sorted(records, key=lambda r: r[0]):
        out += [f"### `{name}`", "", d, "" if d else None, f"Source: `{src}`", "", "| Key | Field | Type | Meaning |", "|---:|---|---|---|"]
        out = [x for x in out if x is not None]
        for k, n, t, fd in fields:
            out.append(f"| {k} | `{n}` | `{t}` | {fd} |")
        out.append("")
    out += ["## Enumerations", ""]
    for name, d, variants, src in sorted(enums, key=lambda e: e[0]):
        out += [f"### `{name}`", "", d, "" if d else None, f"Source: `{src}`", "", "| Code | Name | Meaning |", "|---:|---|---|"]
        out = [x for x in out if x is not None]
        for c, t, vd in variants:
            out.append(f"| {c} | `{t}` | {vd} |")
        out.append("")
    return "\n".join(l for i, l in enumerate(out) if not (l == "" and out[i - 1] == "" and i > 0)) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("docs/generated/RECORDS.md is out of date; run tools/gen_records.py", file=sys.stderr)
            sys.exit(1)
        print("docs/generated/RECORDS.md is current")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({text.count(chr(10))} lines)")


main()
